### ISSUE TITLE
Make JSON parsing faster

### ISSUE THREAD

**Issue by japhb** [Raku/nqp#101]
One good test case would be JSON::Tiny parsing Panda's projects.json.  Panda includes a projects.json.bootstrap which is a very small subset of this, and downloads the full sized version separately.

The full Panda projects.json file is fairly whitespace-compressed; if you need a large file of pretty-printed JSON to optimize whitespace-heavy parsing, the perl6-bench timing function produces these.

**Comment by lizmat** [comment]
[`JSON::Fast`](https://modules.raku.org/dist/JSON::Fast:cpan:TIMOTIMO) has basically taken over from `JSON::Tiny`.  Created as a faster drop-in replacement for `JSON::Tiny`, it has had several iterations of speed improvements itself.  So I guess it is safe to close this issue now.
