### ISSUE TITLE
Can't build against externally-built moar backend (with patch)

### ISSUE THREAD

**Issue by ChoHag** [Raku/nqp#239]
MAST/Ops.nqp and MAST/Nodes.nqp can't be found if Moar has been built and installed in an unexpected location. Luckily Moar itself knows where they are by way of nqp::backendconfig().

Patches can't be uploaded; see http://paste.scsys.co.uk/495786?tx=on

**Comment by coke** [comment]
The paste is no longer found.

Can you please detail what you mean by "unexpected location"? I've built moar/nqp separately before and had no trouble.

**Comment by coke** [comment]
No response, paste still gone; closing ticket. Please feel free to re-open if needed
