### ISSUE TITLE
nqp lacks automated testing on OSX environment

### ISSUE THREAD

**Issue by titsuki** [Raku/nqp#405]
The windows version of this issue is already posted: https://github.com/perl6/nqp/issues/372

**Comment by usev6** [comment]
If I'm not mistaken, nqp is tested on OS X / macOS nowadays:
* https://github.com/Raku/nqp/blob/f23b6aca69/azure-pipelines.yml#L46-L63 and
* https://github.com/Raku/nqp/blob/f23b6aca69/azure-pipelines.yml#L185-L215

So, could this issue be closed?

**Comment by MasterDuke17** [comment]
Yep, Linux/Windows/MacOS are all tested.
