### ISSUE TITLE
Flagged as vulnerable

### ISSUE THREAD

**Issue by zoffixznet** [Raku/nqp#437]
Github flagged this repo:

"We found a potential security vulnerability in one of your dependencies.
A dependency defined in nqp-runtime/package-lock.json has known security vulnerabilities and should be updated."

![untitled](https://user-images.githubusercontent.com/5747918/39336243-6df15c46-4984-11e8-8c8b-ab4f32c7fd20.png)

**Comment by zoffixznet** [comment]
@pmurias does it look like something from JS backend?

**Comment by AlexDaniel** [comment]
This was brought up again today: http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-07-25#l2

**Comment by AlexDaniel** [comment]
And again: http://colabti.org/irclogger/irclogger_log/perl6?date=2018-08-21#l161

**Comment by ajs** [comment]
This error indicates that we're depending on a JavaScript package version that has a known vulnerability. Given the specific package (which is probably revealed by that button you show in your screenshot) these instructions can probably help:

https://stackoverflow.com/questions/49582891/proper-way-to-fix-potential-security-vulnerability-in-a-dependency-defined-in-pa

After that, as long as tests continue to pass, I say declare victory.

**Comment by coke** [comment]
I can't see this warning on the repository anymore on the front page or in settings.
