### ISSUE TITLE
jvm: unhandled exception

### ISSUE THREAD

**Issue by ghost** [Raku/nqp#526]
https://nurmi-labs.blogspot.com/2019/04/perl6.html

https://nurmi-labs.blogspot.com/2018/10/jdk.html

running BACKENDS=moar,jvm ./nqp.SlackBuild

Unhandled exception: java.lang.BootstrapMethodError: call site initialization exception

...

make: *** [gen/jvm/stage1/QAST.jar] Error 1

**Comment by usev6** [comment]
I'm afraid we won't be able to find out what was wrong here -- or more to the point, if the problem is still relevant today. The links don't work any longer.

I'm closing the issue as "Won't fix"/"Can't repro".
