### ISSUE TITLE
Local '__lowered_lex....' already declared when compiling NQP

### ISSUE THREAD

**Issue by linxdev01** [Raku/nqp#552]
I'm ruinning into an issue compiling NQP from source.  I've tried 2018.06, 2019.03 and fresh pul from the repo.  

I'm using 
 libuv-1.29.1
 moarvm-2019.03

I'm doing this on CentOS 5.11 (final)

Is there  asimple test I can do to verify the MoarVM install works before attempting NQP compile?

`
/opt/cs/usr/pkg/i586/perl-5.22.3-4/usr/bin/perl -MExtUtils::Command -e mkpath gen/moar/stage1/gen
/opt/cs/usr/pkg/i586/perl-5.22.3-4/usr/bin/perl tools/build/gen-cat.pl moar src/how/Archetypes.nqp src/how/RoleToRoleApplier.nqp src/how/NQPConcreteRoleHOW.nqp src/how/RoleToClassApplier.nqp src/how/NQPCurriedRoleHOW.nqp src/how/NQPParametricRoleHOW.nqp src/how/NQPClassHOW.nqp src/how/NQPNativeHOW.nqp src/how/NQPAttribute.nqp src/how/NQPModuleHOW.nqp src/how/EXPORTHOW.nqp  > gen/moar/stage1/nqpmo.nqp
/opt/cs/usr/bin/moar --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --setting=NULL --no-regex-lib --target=mbc \
    --output=gen/moar/stage1/nqpmo.moarvm gen/moar/stage1/nqpmo.nqp
Local '__lowered_lex_1.460668967897818e+268' already declared
   at gen/moar/stage2/QAST.nqp:4775  (src/vm/moar/stage0/QAST.moarvm:register_local)
 from gen/moar/stage2/QAST.nqp:4706  (src/vm/moar/stage0/QAST.moarvm:add_param)
 from gen/moar/stage2/QAST.nqp:6067  (src/vm/moar/stage0/QAST.moarvm:compile_var)
 from gen/moar/stage2/QAST.nqp:6022  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5271  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5155  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5920  (src/vm/moar/stage0/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5864  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5155  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5920  (src/vm/moar/stage0/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5528  (src/vm/moar/stage0/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5507  (src/vm/moar/stage0/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5456  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5155  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5920  (src/vm/moar/stage0/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5864  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5155  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5920  (src/vm/moar/stage0/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5864  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5155  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5920  (src/vm/moar/stage0/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5528  (src/vm/moar/stage0/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5507  (src/vm/moar/stage0/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5456  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5271  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5155  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5920  (src/vm/moar/stage0/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5864  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5155  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5920  (src/vm/moar/stage0/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5864  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5155  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5920  (src/vm/moar/stage0/QAST.moarvm:compile_all_the_stmts)
 from gen/moar/stage2/QAST.nqp:5528  (src/vm/moar/stage0/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5507  (src/vm/moar/stage0/QAST.moarvm:)
 from gen/moar/stage2/QAST.nqp:5456  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5271  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5159  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:5299  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5271  (src/vm/moar/stage0/QAST.moarvm:compile_node)
 from gen/moar/stage2/QAST.nqp:5159  (src/vm/moar/stage0/QAST.moarvm:as_mast)
 from gen/moar/stage2/QAST.nqp:4895  (src/vm/moar/stage0/QAST.moarvm:to_mast)
 from gen/moar/stage2/QAST.nqp:6641  (src/vm/moar/stage0/QAST.moarvm:to_mast)
 from gen/moar/stage2/NQPHLL.nqp:443  (src/vm/moar/stage0/NQPHLL.moarvm:mast)
 from gen/moar/stage2/NQPHLL.nqp:1794  (src/vm/moar/stage0/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:1830  (src/vm/moar/stage0/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1833  (src/vm/moar/stage0/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1819  (src/vm/moar/stage0/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1519  (src/vm/moar/stage0/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1774  (src/vm/moar/stage0/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1699  (src/vm/moar/stage0/NQPHLL.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1625  (src/vm/moar/stage0/NQPHLL.moarvm:command_line)
 from gen/moar/stage2/NQP.nqp:4124  (src/vm/moar/stage0/nqp.moarvm:MAIN)
 from gen/moar/stage2/NQP.nqp:4119  (src/vm/moar/stage0/nqp.moarvm:<mainline>)
 from <unknown>:1  (src/vm/moar/stage0/nqp.moarvm:<main>)
 from <unknown>:1  (src/vm/moar/stage0/nqp.moarvm:<entry>)
make[2]: *** [Makefile:242: gen/moar/stage1/nqpmo.moarvm] Error 1

`

Thanks,
Chris

**Comment by vrurg** [comment]
@linxdev01 Could you, pls, provide more info on how did you build? How did you install `moar`? What command lines you used for `Configure.pl`?

**Comment by linxdev01** [comment]
The build is targeted for a root tree in /opt.  I'm using the prefix
argument for every package.

This is CentOS 5.11 with GCC 4.1.2 compiling 32 bit with i586
optimizations.  The roo tree in /opt/<dir> is tar'ed up to be loaded on one
of 2 possible devices.  One is RDC, RISC that acts at i586.  The other is
an Intel J1900.  Even though the J1900 is capable of 64bit I compile
nothing at this time for 64bit.

Configure of MoarVM:

      PP=/opt/cs
       LANG=C \
        PKG_CONFIG_PATH=${PP}/usr/lib/pkgconfig \
        CPPFLAGS="-m32 -march=i586 -I${PP}/usr/include" \
        CFLAGS="-m32 -march=i586 -I${PP}/usr/include" \
        LDFLAGS="${LDFLAGS}" \
        ${PERL} ./Configure.pl \
                --prefix=${PP}/usr  \
                --debug \
                --cc=gcc \
                --has-libffi \
                --has-libuv \
                --pkgconfig=${PP}/usr/bin/pkg-config
        sed -i 's#-Werror=declaration-after-statement##g' Makefile
        sed -i 's#-Werror=pointer-arith##g' Makefile

libffi and libuv are also built and installed in $PP

I've attached build-moar.log for that.

The NQP build is created the same way:

  LANG=C \

  PATH=${PP}/usr/bin:${PATH} \

  LD_LIBRARY_PATH="${PP}/lib:${PP}/usr/lib" \

  PKG_CONFIG_PATH=${PP}/usr/lib/pkgconfig \

  CPPFLAGS="-m32 -march=i586 -I${PP}/usr/include" \

  CFLAGS="-m32 -march=i586 -I${PP}/usr/include" \

  ${PP}/usr/bin/perl Configure.pl \

    --ignore-errors \

    --backends=moar \

    --with-moar=${PP}/usr/bin/moar \

    --prefix=${PP}/usr


I've attached the build-nqp.log for nqp

I don't think the installation method could be a probly, but I don't know
much about Moar and NQP.  I'm using
GNU Stow wrapped up in a management framework I created.  It's sort of like
SCO OpenServer's software object model of managing packages.
The only problems I've had with this is when programs during build or
install follow symbolic links and use the real path instead of the link
path.
Python does this.  A build of GCC will also do this.

The full build of the tree contains 430 Perl 5 modules and perl-5.22.3.
The bulk of the work these devices do is coded in Perl 5.  Easily a million
lines of code, maybe more.  My goal is to start investigating the
transition to 6.

**Comment by vrurg** [comment]
The `build-nqp.log` looks incomplete as it doesn't contain any error messages. Also, I would avoid using `--ignore-errors`. Better have `Configure` failing that not building correctly.

Anyway, let's check if it's a platform-dependent problem. Could you do a fresh clone of `nqp` in a separate directory and simply do `perl Configure.pl --gen-moar && make`?

**Comment by AlexDaniel** [comment]
Any news on this?

**Comment by vrurg** [comment]
@AlexDaniel No news on my side. BTW, I was recently testing the build on a centOS 7.6, passed successfully. Considering how much it lags behind other *nix'es, I'm afraid 5.11 version could be too expensive to support.

**Comment by usev6** [comment]
Given that a) there was no update on this issue for the last two years, b) even CentOS 6 has reached end of support by now (on 2020-11-30) and c) the build works on CentOS 7, IMHO it doesn't make sense to keep this issue open any longer. So, I'm going to close it now. (I hope, that's ok for everyone.)
