### ISSUE TITLE
Relocatability seems to be broken on Windows

### ISSUE THREAD

**Issue by Prince213** [Raku/nqp#626]
```
X:\>nqp hello_world.nqp
Unhandled exception: While looking for 'C:\projects\rakudo-bin\prefix\share\nqp\lib\nqp.moarvm': no such file or directory

X:\>nqp --version
Unhandled exception: While looking for 'C:\projects\rakudo-bin\prefix\share\nqp\lib\nqp.moarvm': no such file or directory
```
Platform: Windows 10
Version of NQP & MoarVM: 2020.05
The scripts used to make the binaries can be found at https://github.com/Prince213/rakudo-bin and the binaries themselves can be found at https://ci.appveyor.com/project/Prince213/rakudo-bin.

Passing the undocumented `--relocatable` option to Configure.pl didn't help.

**Comment by Prince213** [comment]
FYI, NQP version 2020.02.1 also has this problem.

**Comment by patrickbkr** [comment]
@Prince213: I can not reproduce this. Neither on 2020.02.1 nor on 2020.05. I tried both, how I typically compile MoarVM and NQP and using the commands you used in your script. I always renamed the install directory after installation.

I did manage to get the same error message by leaving off the `--relocatable` flag from the NQP `Configure.pl` call.

Can you give it another try making sure you pass the `--relocatable` flag to the Configure.pl of both MoarVM and NQP?

Also can you paste the complete rule for the `$(M_INST_NQP)` target in the nqp `Makefile`? (6 lines) Should be around line 620 or so.

**Comment by Prince213** [comment]
I've just tried the 2020.05 x64 binary on a fresh install of Windows 10 x64, and the problem disappeared. Which probably indicates that there's something wrong with my system. BTW do you know how I can make nqp show verbose information on this situation?

**Comment by patrickbkr** [comment]
Ping @vrurg wrt verbose build information

**Comment by vrurg** [comment]
@Prince213 what kind of verbose information? Could you, pls, elaborate?

**Comment by Prince213** [comment]
Never mind. A symbolic link will fix the problem.
