### ISSUE TITLE
Parse error when a '<.panic(' ending '>' is moved to the next line

### ISSUE THREAD

**Issue by tbrowder** [Raku/nqp#632]
Line 21 of file "src/HLL/sprintf.nqp" is a very long line ending with the following characters:

```
, self.orig)))> ]
```

If the line is wrapped with a newline before the '>', the build fails with the following message:

```
$ make
+++ Preparing MOAR build directories
++++++ Building MOAR backend
+++ Generating	gen/moar/stage1/NQPHLL.nqp
+++ Compiling	gen/moar/stage1/NQPHLL.moarvm
Unable to parse expression in metachar:sym<assert>; couldn't find final '>'  at line 3039, near "\n> ]\n     "
   at gen/moar/stage2/NQPHLL.nqp:1026  (src/vm/moar/stage0/NQPHLL.moarvm:panic)
 from gen/moar/stage2/NQPHLL.nqp:1038  (src/vm/moar/stage0/NQPHLL.moarvm:FAILGOAL)
... 
```

The original line is shown here in its entirety:

```
                || <.panic("'" ~ nqp::substr(self.orig,1) ~ "' is not valid in sprintf format sequence '" ~ self.orig ~ "'", nqp::hash('BAD_DIRECTIVE', nqp::hash('DIRECTIVE', nqp::substr(self.orig, 1), 'SEQUENCE', self.orig)))> ]
```

OS: Debian 10 Buster
nqp -v: This is nqp version 2020.05 built on MoarVM version 2020.05

**Comment by jnthn** [comment]
White space is generally not allowed inside of assertions. The error could be better, though - and the Rakudo output when we put in whitespace in some other circumstances (probably the NQP one) is far from ideal:

```
$ perl6 -e '/<foo = bar>/'
===SORRY!===
Unrecognized regex metacharacter = (must be quoted to match literally)
at -e:1
------> /<foo⏏ = bar>/
Unrecognized regex metacharacter   (must be quoted to match literally)
at -e:1
------> /<foo =⏏ bar>/
Unable to parse expression in metachar:sym<assert>; couldn't find final '>' (corresponding starter was at line 1)
at -e:1
------> /<foo = ⏏bar>/
```

So certainly there's various changes to be more helpful here.

**Comment by tbrowder** [comment]
Good to know, thanks. I'll take a closer look.

**Comment by tbrowder** [comment]
Hm, I think I will have to create a new stage0 but I need a good test first according to the docs. The test might be a challenge. Suggestions welcome.

**Comment by coke** [comment]
The PR for this was merged in 2020; Closing ticket.
