### ISSUE TITLE
`fileexecutable` returns incorrect value in Linux systems (Alpine, Debian) when the user is root.

### ISSUE THREAD

**Issue by JJ** [Raku/nqp#652]
Seen initially in [this test](https://github.com/Raku/ecosystem/runs/933622247), in Alpine Linux the `fileexecutable` function seems to always return `True`
![Captura de pantalla de 2020-08-01 09-48-50](https://user-images.githubusercontent.com/500/89097113-49a46d80-d3dc-11ea-8c82-729263bbeebb.png)
Alpine is used in many test environments, included that one in the ecosystem.

**Comment by gfldex** [comment]
Same problem on Debian but only for user root. So this might not depend on the OS.

**Comment by JJ** [comment]
This also happens for root. Still a bug, but at least it's got a workaround. I'll rebuild the containers to avoid that. Thanks.
