### ISSUE TITLE
Rakudo's install-dist.p6 fails with 

### ISSUE THREAD

**Issue by dod38fr** [Raku/nqp#675]
Hi

On Debian, Rakudo's `install-dist.p6` fails with:

```
Unhandled exception: Missing or wrong version of dependency 'gen/moar/stage2/MASTNodes.nqp' (from 'gen/moar/Pod.nqp')
```
Looks like nqp's build system no longer install nqp files in `/usr/share/nqp/lib/` (although moarvm files are installed there).

I've worked around this issue by running the following line after `make install`:
```
cp -n gen/moar/stage2/*.nqp debian/tmp/usr/share/nqp/lib/
```
For more details please see [Debian bug 971617](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971617)

All the best

**Comment by patrickbkr** [comment]
Did you use the `--nqp-home=/some/other/folder` Configure.pl flag? If yes, are the missing files installed there?

**Comment by dod38fr** [comment]
Hi

Configure.pl is run with `--backends=moar --prefix=/usr`, install phase is done with `make -j4 install DESTDIR=/<<BUILDDIR>>/nqp-2020.09\+dfsg/debian/tmp AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true"`

You can find the build log [there](https://buildd.debian.org/status/fetch.php?pkg=nqp&arch=amd64&ver=2020.09%2Bdfsg-2&stamp=1601308951&raw=0)

All the best

**Comment by dod38fr** [comment]
Sorry, my bad.

I've, again, been misled by the `Missing or wrong version of dependency 'gen/moar/stage2/MASTNodes.nqp'`error message. 
I've checked nqp package 2020.06-1 and this package does not deliver `MASTNodes.nqp`.

The error was caused by the fact that `nqp` package was rebuilt in Debian infrastructure, but `rakudo` package was not.

This tight coupling between nqp and rakudo is a real PITA. This is not the first time I trip on this problem, and it's probably not the last time. I really hope you'll be able to improve this.

Sorry for the noise

**Comment by patrickbkr** [comment]
Just to make sure I understand the failure mode correctly: You had a working installation of MoarVM, NQP and Rakudo. Then you updated NQP. As a result of that update the previously installed Rakudo did not work anymore. Correct?

**Comment by dod38fr** [comment]
Rakudo breaks after I update nqp using Debian package (nqp 2020.09+dfsg-3).

On the other hand, rebuilding and re-installing nqp package does **not** break Rakudo. :confused:

**Comment by patrickbkr** [comment]
So installing Moar 2020.06 (debian package) + NQP 2020.06 (debian package) + Rakudo 2020.06 (debian package), then installing NQP 2020.09 (debian package) breaks Rakudo.

While installing Moar 2020.06 (from source) + NQP 2020.06 (from source) + Rakudo 2020.06 (from source), then installing NQP 2020.09 (from source) keeps Rakudo working?

I probably misunderstand...

**Comment by dod38fr** [comment]
No exactly.

Since this issue is rather confusing, I've done some more tests.

First I've purged all packages and then re-installed rakudo using
Debian/sid packages.

This breaks:
- moarvm 2020.09+dfsg-1 (official debian package)
- nqp 2020.09+dfsg-3 (official debian package)
- rakudo 2020.09+dfsg-1 (official debian package built with nqp 2020.09+dfsg-**1**)

Then I've rebuilt and installed nqp using the Debian package source.

This breaks:
- moarvm 2020.09+dfsg-1 (official debian package)
- nqp 2020.09+dfsg-3 (same source, rebuilt locally)
- rakudo 2020.09+dfsg-1 (official debian package built with nqp 2020.09+dfsg-**1**)

Then I've rebuilt and installed rakudo using the Debian package source.

This does **not** break:
- moarvm 2020.09+dfsg-1 (official debian package)
- nqp 2020.09+dfsg-3 (same source, rebuilt locally)
- rakudo 2020.09+dfsg-1 (same source, rebuilt locally)

To better characterize this behavior, I've re-installed official nqp package.

This does **not** break:
- moarvm 2020.09+dfsg-1 (official debian package)
- nqp 2020.09+dfsg-3 (official debian package)
- rakudo 2020.09+dfsg-1 (same source, rebuilt locally during the previous step)

Hope this helps

**Comment by patrickbkr** [comment]
@niner Can you make sense of this? Is it possible that NQP fails to be reproducable and thus causes these errors?

**Comment by niner** [comment]
On Dienstag, 6. Oktober 2020 15:30:52 CEST Dominique Dumont wrote:
> From Debian point of view, nap is [not
> reproducible](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/
> amd64/diffoscope-results/nqp.html) (although we may have a different
> definition of reproducible build: Debian aims to produce bit for bit
> identical package when building nqp with the same source)

Are these builds really the same source in the same directory unmodified? A 
rebuild of nqp should give a bit identical result.

**Comment by dod38fr** [comment]
These builds are done in Debian build system from the same source package. They may be done on different system and are done in different directories:

```
-I: Running cd /build/1st/nqp-2020.09+dfsg/ && env PATH="/usr/sbin:/usr/bin:/sbin:/bin:/usr/games" HOME="/nonexistent/first-build" dpkg-buildpackage -us -uc -b
+I: Running cd /build/2/nqp-2020.09+dfsg/2nd/ && env PATH="/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/i/capture/the/path" HOME="/nonexistent/second-build" dpkg-buildpackage -us -uc -b
```

This [link](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/nqp.html) provides a diff between  2 build logs of nqp 2020.09+dfsg-3

This setup is specific to Debian reproducible build test infrastructure.  The packages built there are **not** used as official Debian package.

The build logs of official Debian nqp package are [there](https://buildd.debian.org/status/logs.php?pkg=nqp&arch=amd64).

**Comment by niner** [comment]
On Dienstag, 6. Oktober 2020 15:53:12 CEST Dominique Dumont wrote:
> They may be done on different system and are done in different directories:

Then that's not a real test of a rebuild. 
`#·This·file·automatically·generated·by·/build/1st/nqp-2020.09+dfsg/tools/
build/gen-cat.pl`
is part of the source. The source changes, so the build result changes

**Comment by lizmat** [comment]
Perhaps Debian is taking the "reproducible builds" a bit further?

**Comment by dod38fr** [comment]
I don't see why the build location should be considered as part of the source. This location is not part of nqp tarball.

In other words, Debian defines the source as the results of `find .`, not of `find $PWD`...

**Comment by niner** [comment]
On Dienstag, 6. Oktober 2020 16:36:02 CEST Dominique Dumont wrote:
> I don't see why the build location should be considered as part of the
> source. This location is not part of nqp tarball.

I showed how it becomes part of the compiled source.

You brought up that debian result when trying to figure out your rebuild 
issue. I explained, why that result isn't helpful for the diagnosis. Nothing 
more.

**Comment by dod38fr** [comment]
On the other hand, we can see in Debian build logs that `nqp 2020.09+dfsg-1` and `nqp 2020.09+dfsg-3` were built in different directories:

* `nqp 2020.09+dfsg-1` was built in `/build/nqp-796ojj/nqp-2020.09+dfsg`
* `nqp 2020.09+dfsg-3` was build in `/build/nqp-Xeblqj/nqp-2020.09+dfsg`

Knowing that rakudo `2020.09+dfsg-1` from official Debian package:
* was built with `nqp 2020.09+dfsg-1`
* runs fine with `nqp 2020.09+dfsg-1`
* breaks with `nqp 2020.09+dfsg-3`

I assume that the last point is explained by the fact that `nqp 2020.09+dfsg-3` is not built in the same directory than `nqp 2020.09+dfsg-1`.

Is that correct ?

**Comment by niner** [comment]
> I assume that the last point is explained by the fact that `nqp
> 2020.09+dfsg-3` is not built in the same directory than `nqp
> 2020.09+dfsg-1`.
> 
> Is that correct ?

Yep, that would make sense. Considering that this is just about a comment 
added by a tool in the build system, this hypothesis should be pretty easy to 
test and if it holds, the issue trivial to fix.

**Comment by dod38fr** [comment]
> Considering that this is just about a comment added by a tool in the build system, this hypothesis should be pretty easy to test and if it holds, the issue trivial to fix

Err, I'm not sure which build system you are referring to. Is that Debian's or nqp's ?

**Comment by niner** [comment]
> Err, I'm not sure which build system you are referring to. Is that Debian's or nqp's ?
The whole problem is that it's telling us exactly that :) `#·This·file·automatically·generated·by·/build/1st/nqp-2020.09+dfsg/tools/build/gen-cat.pl`

**Comment by dod38fr** [comment]
Oh... right...

ok, I'm going to patch Debian's nqp and see how this pans out...

**Comment by dod38fr** [comment]
Local tests confirm that changing the build directory of nap package no longer breaks rakudo. 

Thanks for your help :-)

**Comment by tidux** [comment]
Fedora 39's package fails with this same error.

**Comment by raiph** [comment]
Hi @tidux,

Thanks for adding the comment.

Afaik: this error is a pretty generic one; fixing it is platform specific; it could arise again on debian, and if so it would make sense for us to reopen this issue; but you're reporting it on fedora 39, and that's sufficiently different from debian that it doesn't make sense to me to reopen this issue; someone else might see things differently and reopen this issue, but in the meantime, or if that doesn't happen, you might wish to do something about this problem as follows.

If you do want to do something further about this problem, my advice is that you open a new issue. If you do, please provide pertinent system details and messages in your initial comment. It would be great if you know and figure out enough to workaround the problem as @dod38fr did (see their initial comment in this issue), but regardless, I think that filing a new issue with what you know is the thing to do for the time being if you wish to draw attention to the problem.
