### ISSUE TITLE
Issues with CI

### ISSUE THREAD

**Issue by JJ** [Raku/nqp#693]
You probably have not noticed, but Travis has been disabled for one week already, since the Raku organization has exhausted its free *and* additional credits we obtained through their open source program. This means no testing until they are replenished, and from what I have heard, new direction is not keen on giving out credits, apparently. At any rate, two months to burn through the allotment of credits is a bit too much, and the main culprit [is the JVM builds](https://travis-ci.com/github/Raku/nqp/jobs/467775333), which take ~15 minutes every time (we had 3500 minutes, so that 0.4% of the credit _every build_, without including the other two tests).
So we need, in the near term, to speed it up, in the longer term, to take it somewhere else. In order to speed it up, we can use the Travis cache. Since this is bulding jars, not all of them might be built all the time, so we might activate the cache to get it working again. That will shave/save a bit of time every time, although not clear how much.
In the longer term, we should try and move some tests elsewhere. There's much more time in GitHub itself, but other possibilities include GitLab (where we have free credits too), Circle, or any other.
Additionally, I'll try and check the other builds too. Possibly they can be sped up with a pre-built moarvm; not a lot, but it might save a minute or two. Everything counts.

**Comment by zaucker** [comment]
- Why not use GitHub actions?
- Caching is certainly something that can help a lot if appropriate for the particular test suite.
- Another option would be our own CI host. At Oetiker+Partner we use [Drone CI](https://www.drone.io/) for some projects.

**Comment by JJ** [comment]
Anything that reduces the consumption of Travis credits is welcome. Even taking this repo off Travis completely, since this (and Raku/doc) are the ones that spend the most credits.
![Captura de pantalla de 2021-01-10 10-38-29](https://user-images.githubusercontent.com/500/104119507-0ad1f680-5330-11eb-9543-38e526dddac2.png)
30% of the credits have been spent in this repo (As you see, Raku/doc is the one that has spent the most)
The baseline is, we can't keep of relying on Travis for heavyweight repos like this one.

**Comment by Altai-man** [comment]
We have an Azure workflow now, so Travis can be simply disabled and so be it. It could be done for months now, really, but nobody was brave enough.

**Comment by Altai-man** [comment]
If docs use Travis, we should migrate to Azure as well.

**Comment by patrickbkr** [comment]
I agree to Altai-Man. Azure is configured to entirely replace Travis (and the other CIs we have configured). I see no reason to invest time to keep travis alive.

**Comment by usev6** [comment]
Is this still relevant? I didn't follow the restructuring of the CI setup closely, but I think Travis isn't used any longer.

**Comment by MasterDuke17** [comment]
Correct, closing.
