### ISSUE TITLE
Compilation fails on macOS 13

### ISSUE THREAD

**Issue by fxcoudert** [Raku/nqp#784]
Compilation on macOS Ventura leads to:

```
==> perl Configure.pl --backends=moar --prefix=/opt/homebrew/Cellar/nqp/2022.07 --with-moar=/opt/homebrew/opt/moarvm/bin/moar
  fatal: not in a git directory
  fatal: not in a git directory
  Found /opt/homebrew/opt/moarvm/bin/moar version 2022.07, which is new enough.
  Cleaning up ...
  You can now use 'make' to build NQP.
  After that, 'make test' will run some tests and
  'make install' will install NQP.
  ==> make
  ++++++ Building MOAR backend
  +++ Preparing MOAR build directories
  +++ Generating	gen/moar/stage1/nqpmo.nqp
  +++ Compiling	gen/moar/stage1/ModuleLoader.moarvm
  sh: gen/moar/stage1/nqpmo.nqp: No such file or directory
  +++ Generating	gen/moar/stage1/NQPCORE.setting
  make: *** [gen/moar/stage1/nqpmo.nqp] Error 1
  make: *** Waiting for unfinished jobs....
```

**Comment by vrurg** [comment]
First of all, do you have permissions for the directory?

**Comment by fxcoudert** [comment]
The directory I'm building is a temporary directory, where I have the correct permissions, and the same is true of the `prefix`. The same build (through Homebrew) works on Intel, and on other macOS versions.

**Comment by vrurg** [comment]
Try `--no-silent-build` for Configure.pl and make sure all paths and command lines are correct. Or do so manually by inspecting `Makefile`.

**Comment by chenrui333** [comment]
- The latest release build actually works for us Homebrew/homebrew-core#117300, I think we can close this issue now.
